### ISSUE TITLE
Doesn't Work Anymore in Chrome

### ISSUE THREAD

**Issue by carosati3** [jordam/Portify.JS#2] opened 2016-02-12 19:12 UTC
I used your tool yesterday and it worked great in Chrome. Today it doesn't work. It gets to loading up Play Music and then nothing really happens after I name the playlist.

**Comment by jordam** [comment] 2016-02-13 22:13
Duplicate of #3 if i'm not mistaken

**Closed as completed by jordam** 2016-02-13 22:13 UTC

**Comment by wwwwiiiillll** [comment] 2017-11-13 08:50
you can use MusConv.com tool,it will work
